// Moving a piece of one bench onto another.
//
// The clipboard lives in the workspace, not in a document, because its whole purpose is to
// outlive the document it came from — copying half a double-pass out of one tab and into
// another is the reason tabs were worth building.
//
// Pure functions here; the wiring is in `useClipboard`. What gets copied is the *selection*
// as xyflow reports it (`node.selected`), plus the user-drawn edges whose two ends are both
// in that selection: an edge to something you did not copy has nowhere to land.
import type { Node, Edge } from '@xyflow/react';
import type { OpticalNodeData, BeamEdgeData } from '../types/components';
import { PX_PER_INCH } from '../physics/scale';

export interface ClipboardContent {
  nodes: Node<OpticalNodeData>[];
  edges: Edge<BeamEdgeData>[];
  /** Which document it came from, so pasting back into that one can offset itself. */
  sourceDocId: string;
}

/**
 * Offset applied when pasting into the document the copy came from: one breadboard hole, so
 * the new components are visibly separate from the originals rather than exactly on top of
 * them. A paste into a *different* document keeps the original coordinates, because the
 * geometry relative to the rest of the bench is the thing worth preserving.
 */
export const PASTE_OFFSET_PX = PX_PER_INCH;

/** Fresh id for a pasted node. Matches the canvas's own scheme closely enough to read. */
let pasteCounter = 1;
const pastedId = () => `paste_${Date.now()}_${pasteCounter++}`;

/**
 * What the selection amounts to, or null if there is nothing worth copying.
 *
 * Phantom beam endpoints are excluded — they are regenerated by every trace and are not
 * components — and so are the routing edges, which the tracer rebuilds.
 */
export function collectSelection(
  nodes: Node<OpticalNodeData>[],
  edges: Edge<BeamEdgeData>[],
  sourceDocId: string,
): ClipboardContent | null {
  const picked = nodes.filter(n =>
    (n as { selected?: boolean }).selected === true
    && n.type !== 'beam_endpoint',
  );
  if (picked.length === 0) return null;

  const ids = new Set(picked.map(n => n.id));
  const internal = edges.filter(e =>
    !e.id.startsWith('auto_') && ids.has(e.source) && ids.has(e.target),
  );

  return {
    // Copies, so later edits to the originals cannot reach into the clipboard.
    nodes: picked.map(n => ({ ...n, data: { ...n.data } as OpticalNodeData })),
    edges: internal.map(e => ({ ...e })),
    sourceDocId,
  };
}

/**
 * Turn clipboard content into nodes and edges ready to insert.
 *
 * Every node gets a fresh id — pasting into the source document would otherwise collide —
 * and the copied edges are rewired onto the new ids. The pasted nodes come back selected
 * and the rest deselected, so a paste can be dragged straight away and pasting twice does
 * not stack silently.
 */
export function materialise(
  content: ClipboardContent,
  targetDocId: string,
): { nodes: Node<OpticalNodeData>[]; edges: Edge<BeamEdgeData>[] } {
  const offset = content.sourceDocId === targetDocId ? PASTE_OFFSET_PX : 0;
  const idMap = new Map<string, string>();
  for (const n of content.nodes) idMap.set(n.id, pastedId());

  const nodes = content.nodes.map(n => ({
    ...n,
    id: idMap.get(n.id)!,
    position: { x: n.position.x + offset, y: n.position.y + offset },
    selected: true,
    // Locked components paste unlocked-in-place: the lock is about *this* bench's layout,
    // and a pasted copy has just been moved by definition.
    data: { ...n.data, locked: false } as OpticalNodeData,
    // Dropped so xyflow re-measures rather than trusting a stale size.
    measured: undefined,
    dragging: false,
  })) as Node<OpticalNodeData>[];

  const edges = content.edges.map(e => ({
    ...e,
    id: `paste_${e.id}_${pasteCounter++}`,
    source: idMap.get(e.source)!,
    target: idMap.get(e.target)!,
  }));

  return { nodes, edges };
}

/** How many components are on the clipboard, for a label or a tooltip. */
export function clipboardSize(content: ClipboardContent | null): number {
  return content?.nodes.length ?? 0;
}
